### ISSUE TITLE
Move some non-Guix related scripts to a more general repository

### ISSUE THREAD

**Issue by cbaines** [alphagov/govuk-guix#36]
The `govuk` wrapper script was originally added to this repository to work with the `govuk-system` and `govuk-data` scripts.

That was a couple of years ago now, and in that time other things have emerged that it can work with it. In the `govuk-guix` repository, there is `govuk-connect`, `govuk-config` and `govuk-update-repos`, all of which aren't particularly to do with Guix, but ended up here alongside the wrapper script as it was more convenient. Additionally, things like the `govuk-docker` script in the https://github.com/alphagov/govuk-docker repository also work with the `govuk` wrapper script here.

Now that there's growing interest in using the `govuk connect` tool, I've been considering moving some of the scripts that have so far lived in here to a new repository specifically for command line scripts relating to GOV.UK (the name I'm considering currently is `govuk-cli`).

As I see it, this would have two main benefits: 
 - Make anything in that new repository easier to understand, as it wouldn't be lumped in with all the extra things that the `govuk-guix` repository does. 
 - Make it more feasible to look at distributing the scripts as a gem package (Ruby) and/or a Homebrew thing like the `gds-cli` https://github.com/alphagov/homebrew-gds

This work should complement adding interoperability with the `gds-cli`, so that users of that can easily find out about, and access scripts maintained outside of the `gds-cli`. I've started exploring that here: https://github.com/alphagov/gds-cli/pull/140

**Comment by benthorner** [comment]
This is a good idea - I think we'll get a lot of benefit from `govuk-connect` in particular, if we choose to adopt it and recommend it as a standard tool. What I'm not so keen on is "one CLI to do everything", which I think should be a separate concern to making each individual tool generally available:

   - [against] Given the reasonable size and complexity of something like `govuk-connect`, it seems reasonable that it could be its own repo alongside `govuk-docker`.
   - [against] Having "one CLI" could lead to it being a dumping ground for everyone's favourite commands, which I believe has happened to some extent with the gds-cli.
   - [for] Having separate repos for each tool would make them harder to aggregate into one CLI, and potentially inconsistent in their syntaxes

It may still be valuable to have a single CLI, but it seems more pragmatic to establish an individual use/need for each tool before aggregating them all together. This should also mean we have a better understanding of what people actually want from a single CLI, or if they want it at all.

**Comment by cbaines** [comment]
Sorry for the delay on getting back on this, I missed that there was still some points to continue discussing.

> What I'm not so keen on is "one CLI to do everything", which I think should be a separate concern to making each individual tool generally available:
> 
>   * [against] Given the reasonable size and complexity of something like `govuk-connect`, it seems reasonable that it could be its own repo alongside `govuk-docker`.

Given that the govuk-connect script depends in a way on the `govuk` and `govuk-config` scripts, even if that was in it's own `govuk-connect` Git repository, those other scripts would still need a place to live (and this issue is about moving them out of `govuk-guix`). If those scripts weren't in the same repository as `govuk-connect`, then I wouldn't be sure where to put them.

>   * [against] Having "one CLI" could lead to it being a dumping ground for everyone's favourite commands, which I believe has happened to some extent with the gds-cli.

My thoughts on this are twofold. I can't think of anything else at the moment that would go in to the `govuk-cli` repository, but I also don't see a problem with adding small scripts that are generally useful if the need among GOV.UK developers arises.

> It may still be valuable to have a single CLI, but it seems more pragmatic to establish an individual use/need for each tool before aggregating them all together.

So, I'd like to see things moving away from having a single file (so move away from `govukcli`), as I think the hard restriction of having everything implemented in bash is too restrictive, but I'd still like to see some togetherness hence having some core functionality in a single repository.

Maybe the `-cli` bit is not working out. I went with that name as it matched up with the `gds-cli`, but the repository could also be called `govuk-scripts` if that was less confusing.

> This should also mean we have a better understanding of what people actually want from a single CLI, or if they want it at all.

I guess I see this move here as making the situation less of a "single" CLI, than the current situation. Moving from having a single file, and breaking it up in to some scripts in a Git repository.

**Comment by benthorner** [comment]
@cbaines thanks for following up. I definitely agree we should be aiming to have more than one file! I also like your suggestion of a different name for a single repo, although `govuk-scripts` could be interpreted in a few ways. My main concern is avoiding a single CLI/aggregate script, so:

   - The naming should not imply this exists or that this is the aim
   - Different scripts (and their supporting files) should be clearly separated
   - I think we should avoid a `govuk` script and use `govuk-connect`

Having one repo sounds more reasonable if we follow the above. I'd suggest `govuk-cli-scripts` or similar, which could still evolve into `govuk-cli`. An alternative may be to require people to install dependent scripts manually, but I appreciate that's less convenient.

**Comment by cbaines** [comment]
> My main concern is avoiding a single CLI/aggregate script, so:
> 
>   * The naming should not imply this exists or that this is the aim

I'm not sure I follow what you mean here. Are you saying that the name of the repository shouldn't imply something?

>   * Different scripts (and their supporting files) should be clearly separated

Do you mean separated in to different Git repositories, as in my mind, they are separated. The different scripts are in different files. The `govuk-connect` and `govuk-aws` scripts are also standalone, so they don't have any supporting files.

>   * I think we should avoid a `govuk` script and use `govuk-connect`

I don't have any disagreement with this point in principle, but it seems to me that it'll make it harder for developers on GOV.UK to use them. In particular, removing the `govuk` wrapper script would mean that `govuk connect` runs with whatever Ruby appears first on your PATH, whereas the `govuk` wrapper script makes some attempt to find a more recent Ruby version.

> Having one repo sounds more reasonable if we follow the above. I'd suggest `govuk-cli-scripts` or similar, which could still evolve into `govuk-cli`. An alternative may be to require people to install dependent scripts manually, but I appreciate that's less convenient.

I guess to me `govuk-cli-scripts` suggests that there's a `govuk-cli` thing, and these are some auxiliary scripts. The `govuk-cli` name in abstract is meant to be similar to the `gds-cli` as I'd like to see the two interoperate where it's beneficial, so `govuk-cli` is anything specific to GOV.UK and thus isn't suitable for sitting in the `gds-cli`.

**Comment by cbaines** [comment]
So, the new `govuk-cli` repository has existed for a little while, but moving scripts from `govuk-guix` has somewhat stalled, there's also not much activity in the repository apart from me raising Pull Requests.

I don't have much energy to look more at this at the moment so I think it's best to rollback, in the database sense.

The main impact of this will be the loss of the Homebrew packages, but hopefully this area along with the move of some of these scripts out of `govuk-guix` can be picked up again in the future if there's a clearer path forward.
